config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('', include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('prefer/', views.preferenceTest, name='prefer-test'),
    path('preference/', views.preference, name='prefer'),
    path('movies/', views.recommendList, name='movies'),
    path('movies/list/', views.movieList, name='movie-list'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from . import validators

# 사용자 모델
class User(AbstractUser):
    username = models.CharField(
        max_length=30,
        unique=True,
        null=True,
        validators=[validators.validate_no_special_characters],
        error_messages={"unique": "이미 사용 중입니다."},
    )

    prefer = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.email)

# 영화 모델
class Movie(models.Model):
    movie_id = models.CharField(max_length=30, primary_key=True)
    movie_title = models.CharField(max_length=100)
    release_year = models.CharField(max_length=4)
    poster_img = models.TextField()
    director = models.CharField(max_length=30)
    summary = models.TextField()

    class Meta:
        ordering = ['release_year']

    def __str__(self):
        return f'{self.movie_title} - {self.release_year}'
    

class MovieRating(models.Model):
    rating = models.FloatField()
    movies = models.OneToOneField(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.rating)
    

class Genres(models.Model):
    genres = models.CharField(max_length=30)

    movies = models.ManyToManyField(Movie)
    
    def __str__(self):
        return str(self.movies)
    

class TempPrefer(models.Model):
    iid = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    year = models.CharField(max_length=4)
    rating_avg = models.FloatField()
    poster = models.TextField()
    genres = models.CharField(max_length=100)
    director = models.CharField(max_length=50)
    summary = models.TextField()

    def __str__(self):
        return f'{self.title} - {self.year} - {self.genres}'

movies/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm
from . import validators
from .models import User

class MyCustomLoginForm(LoginForm):
    class Meta:
        model = User
        fields = ['email']
    def login(self, *args, **kwargs):
        # Add your own processing here.

        # You must return the original result.
        return super(MyCustomLoginForm, self).login(*args, **kwargs)
    

class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

    def signup(self, request, user):
        user.email = self.cleaned_data['email']
        user.save

movies/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Movie, MovieRating, Genres, TempPrefer
from .forms import SignupForm, MyCustomLoginForm
import json

# 첫 페이지
def index(request):
    if request.user.is_authenticated is True:
        return redirect('prefer-test')
    return render(request, 'movies/index.html')


# 가입시 선호 영화 선택 창
def preferenceTest(request):
    # 선호영화를 고른사람은 바로 영화 화면으로 리디렉션
    if request.user.prefer != None:
        return redirect('movies')
    
    # 안고른사람은 고를 수 있도록 선호체크 화면으로 랜더링
    return redirect('prefer')


# 첫 회원가입 혹은 로그인 시 선호 작품 선택하게 해주는 뷰
def preference(request):
    if request.method == 'GET':
        movies = TempPrefer.objects.all()
        context = {'movies':movies}
        return render(request, 'movies/preference.html', context)
    elif request.method == 'POST':
        post_data = json.loads(request.body.decode("utf-8"))
        data = post_data.get('text')
        myuser = request.user
        myuser.prefer = data
        myuser.save()
        return redirect('movies')

def recommendList(request):
    if request.user.is_authenticated:

        if request.method == "GET":
            img_ls = [
                "https://an2-img.amz.wtchn.net/image/v2/T7qP_idp-A7AdHCV6-wZBA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56VTJOVE16TlRNNE9EVTVNVEEyTURVaWZRLmZxSThtNU1jQl9HSDFxQ0plZGlUYUxPa1R4WTVwSC1kZGhNWVhISy16anM",
                "https://an2-img.amz.wtchn.net/image/v2/KdZZFDjbAnzNfrYsEH6csQ.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56RTNOalk0TlRjMU1EVTFNamMzTWpVaWZRLkFjc1FZVGZkSHdueEVBX2dpQ20xcnQ3WUhuTDdfLTllQzlYa0l3NWVvVUk",
                "https://an2-img.amz.wtchn.net/image/v2/aYGHhHRw6fLVcy5Z9pW8-Q.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56WTFPVGszTXpJMk56UTNNekkyTURVaWZRLmZVZEdGOEl1cVpFeGJvOWhmMDJzdTFDaHBjQ0pJeHpORElld29Jc2p0RDg",
                "https://an2-img.amz.wtchn.net/image/v2/zMCmf_akyzZCKoQuF309hQ.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56WTRNemt5TkRZNU1qTXpPREE1T1RZaWZRLk55UURqMlJxUTR1WXIwZWppU1hlTVNGVHNzR1hoYk94MzdTZkRtMTBXQ28",
                "https://an2-img.amz.wtchn.net/image/v2/b3vUj5RxXNSMEuv8StYk0w.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56YzFNemd4T0RZek1qSTFORE00TVRnaWZRLk92Z2Z6ZzNrTkFEYXBmOWNHdVQ1YVduZENiMTFUTlpJM0RJZmVvSldZZGc",
                "https://an2-img.amz.wtchn.net/image/v2/CaEoPXXKc7vSOKCFtKa4Yw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56VTRNelUwTVRreU1ESTRORGczTURFaWZRLkg0aGlKX2Q3Q21POTYwT3BZMnlxS1RMS194QzFRbVZ2bXdaNTlfMXdHNU0",
                "https://an2-img.amz.wtchn.net/image/v2/lS7z4u46NJ6QXKaWQwApfw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56WTFPVGt3TVRVek1EYzVNREl5TXpFaWZRLlFrM09TUlpmMC1TQ2NSdkl4ajI3YnQ4V2xGUmU0blNHdlIxNmlScGdqWnM",
                "https://an2-img.amz.wtchn.net/image/v2/YUwgLWf5GjrzQYMDL6wfug.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5USTJPREUzTXpNeE56SXlNVEE1TmpjaWZRLi1YMnQ4bmxvaTI3U0RDMXZBaVJqSEdXWTFsdEREZjVIbTg1NWhYVHh5M1U",
                "https://an2-img.amz.wtchn.net/image/v2/biVpbQFuhi0l3I7YpLDFYw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56VTVPVGM0TnpFMk9USTFNREExTkRZaWZRLjZ5bmxINVNpVk85R240aWNEeUNpWDhqTkNFdElyUjJwdFhjUXFWb2s1WjA",
                "https://an2-img.amz.wtchn.net/image/v2/BDpXAImcYxsTO7JLcCtfkA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56Z3dPRFUyTXpjM01UWXlOakF5TXpJaWZRLkM4MF9IcVF6b3dobnlhNVg2dklnV1VFbWpTRVFia2sydFYxYjlUNGpSWXM",
            ]
            img_ls2 = [
                "https://an2-img.amz.wtchn.net/image/v2/Z6JMMvgh70CwzIIVRGj8Wg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5EUXlNREUwTVRReU56QXlNakU1TVRJaWZRLm9wUnV4R0R5emYzWXBIZndtVGxqbU94SlVCYXkwdk9GT0lBVVpZN3hlaHc",
                "https://an2-img.amz.wtchn.net/image/v2/tkmsakQ3xtdo7JXj6Gogqw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UZzRPREF6TXpjeU5qY3dNREkxTXpraWZRLjU3cGhtemxyblpFdW5jU1BfZy1ycUhNU1VjV19WTDlLSjJITmh3anJPVWM",
                "https://an2-img.amz.wtchn.net/image/v2/981xSWRzzosPOjw7Zeiq-A.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXhMMjVrY0hwak4zZHBaR2gyYVdsMVpXdDRaWE55SW4wLkZfNFk4ek9wMWFTVnQ5TzNsd2loTjZmeTNoWDhqMV9YS0o5NkJ0V25ld0E",
                "https://an2-img.amz.wtchn.net/image/v2/93ikI9PjazpuYaM1HUjj5Q.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16a3pNakF6TnpVeU1URXpPRFUzTVRZaWZRLmY4OUM3dnc4Q09UNElFMllYN00yU2UyaVhNQnYxbzRmWmxOeXdpbmR0WnM",
                "https://an2-img.amz.wtchn.net/image/v2/QqtmKstt8JHnc5QwA98kEQ.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56STVNalE1TWpjek9UUTRNakUxTmpnaWZRLlBIcmNGOWR2YWNQdGpXNjgzZm91WFJnQlpudjdxU1lnU0NZLTJxSzNaWkk",
                "https://an2-img.amz.wtchn.net/image/v2/4vhjmPctbs9uHInWh3pKqw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXhMMnQ1Wm5jd2FITnZhbXh5TVhObVkydHlibVprSW4wLlZuZE5XZXFLUzN3SnhURllYZVdjZXl1emU0WUx2WjBGaFJxN2Z2RzVfekU",
                "https://an2-img.amz.wtchn.net/image/v2/9TrYTXkmKQX3dvgcgi4sIg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5EZzBORE14T0RJeE1qTTNNRFl3TURBaWZRLjVHa1R1Zk12c0I5RnlsWEZDSG5pMUZWdnVvQmNSSU10VVJDMFlocmRlN2s",
                "https://an2-img.amz.wtchn.net/image/v2/HkA9Wh_YWE_YmstdBdptsg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXhMM1Z5YkdKbFpERmpkRzgyWjJoamRYQnBiMjV4SW4wLjBHUzZiZXZaRGdDVlBrMzZyZmpyUDFfM25jRUtDTDJXT2hhRUxOaXR0RFk",
                "https://an2-img.amz.wtchn.net/image/v2/VsbOBHKO4HntnkPqwyKoGA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UZzBOVGM0TkRBMk16TTFPRGcwTVRJaWZRLjV2NVB4VGVkWDZXLUJaUGNoS0NRbkk5anBaMFRMN3hxMDNBb1ZFUFdDZms",
                "https://an2-img.amz.wtchn.net/image/v2/1E9ZN6C7ATEGolUAh_0k_w.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk1UVXhPRGc1TmpZeU9UazFOemd4TmpnaWZRLmJ3OUJObXpHbGRBY1pZMU92aVNqdFVPMmtWakhFZkdCU0UxOUJWQkJ0ZTg",
            ]
            context = {
                'imgs': img_ls,
                'imgs2': img_ls2,
            }
            return render(request, 'movies/recommendation.html', context)

    else:
        return redirect('account_login')



def movieList(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
    }
    return render(request, 'movies/movie-list.html', context=context)

movies/templates/movies/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="Description" content="Enter your description here"/>
    <!-- favicon -->
    <link rel="shortcut icon" href={% static "movies/images/favicon2.png" %}>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css?family=Chakra Petch:300,300i,400,400i,600,600i,700,700i|Chakra Petch:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <link rel="stylesheet" href={% static "movies/css/style.css" %}>
    <link rel="stylesheet" href={% static "movies/css/slide.css" %}>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />

    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>

    <title>WATFLIX</title>
</head>
<body>

    {% block content %} {% endblock %}
    
    {% include './footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/footer.html
<footer>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2023 Copyright 
        <a href="#" target="_blank"> - WATFLIX</a>
      </div>
      <!-- Copyright -->
</footer>

movies/templates/movies/index.html
{% extends "movies/base.html" %}
{% load static %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <!-- <div class="container-fluid"> -->
        <div class="container">
        {% include 'movies/navbar1.html' %}
      </div>
      <!-- </div> -->
      <!-- <center> -->
        <div class="container">
          <div class="hero-text">
            <b><h1 class="landing-title">지금 시작하고</h1></b>
            <p class="hero-p">영화 추천을 받아보세요</p>
            <p>지금 가입하세요</p>
            {% if user.is_authenticated %}
            <a href="{% url 'movies' %}" name="recommendation">
              <button class="btn btn-danger btn-lg">시작하기</button>
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" name="signup">
              <button class="btn btn-danger btn-lg">시작하기</button>
            </a>
            {% endif %}
          </div>
        </div>
      <!-- </center> -->
    </div>
    <div class="container-fluid section-1">
        <div class="row">
            <div class="col-sm-6">
                <h1 style="font-size: 60px;"><b>최신 상영작부터 명작까지</b></h1>
                <p>영화에 대한 모든 것을 추천해드립니다!</p>
                {% if user.is_authenticated %}
                <a class="btn-link" href="movies">
                  <h3>회원이신가요? <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: ;msFilter:;"><path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"></path></svg></h3>
                </a>
                {% else %}
                <a class="btn-link" href="account_login">
                  <h3>회원이신가요? <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24" style="fill: rgba(255, 255, 255, 1);transform: ;msFilter:;"><path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"></path></svg></h3>
                </a>
                {% endif %}
            </div>
            <div class="col-sm-6">
                <img src="{% static 'movies/images/capcap.jpeg' %}" width="500">
            </div>
        </div>
    </div>
{% endblock %}

movies/templates/movies/movie-list.html
{% extends "movies/base.html" %}
{% load static %}

{% block content %}
    <div>
    {% for i in movies %}
        <h1>{{i.movie_title}}</h1>
        <p>{{i.pk}}</p>
        <p>{{i.movie_id}}</p>
        <p>{{i.poster_img}}</p>
        <p>{{i.summary}}</p>
        {{ i.genres_set.value}}
        {% for k in i.genres_set.values %}
        {{k.genres1}}
            <!-- {{k}}{{v}}
            {% if k|first in 'genres' and v is not None %}
                {{ v }} {{ k }}

            {% endif %} -->
        {% endfor %}
 
    {% endfor %}
</div>
    <div class="swiper">
        <div class="swiper-wrapper">
          <div class="swiper-slide"><img src="https://an2-img.amz.wtchn.net/image/v2/T7qP_idp-A7AdHCV6-wZBA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk56VTJOVE16TlRNNE9EVTVNVEEyTURVaWZRLmZxSThtNU1jQl9HSDFxQ0plZGlUYUxPa1R4WTVwSC1kZGhNWVhISy16anM"></div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
          <div class="swiper-slide">Resize me!</div>
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
      </div>
    
      <!-- Swiper JS -->
      <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>

      <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper', {
      slidesPerView: 3,
      direction: getDirection(),
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
      on: {
        resize: function () {
          swiper.changeDirection(getDirection());
        },
      },
    });

    function getDirection() {
      var windowWidth = window.innerWidth;
      var direction = window.innerWidth <= 760 ? 'vertical' : 'horizontal';

      return direction;
    }
  </script>
{% endblock %}

movies/templates/movies/navbar1.html
{% load static %}
{% block navbar %}
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg">
        <div class="container" style="margin-top:15px; padding-left:20px;">
            <a href="{% url 'index' %}" name="Home">
                <img src={% static "movies/images/logo.png" %} width="150">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mx-auto">
                    
                </ul>
                <div class="d-flex">
               
                </div>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

movies/templates/movies/navbar2.html
{% load static %}
{% block navbar %}
<style>
    .custom-nav a {
        color: white;
        font-size: 2rem;
        font-weight: 500;;
    }
</style>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg">
        <div class="container" style="margin-top:15px; padding-left:20px;">
            <a href="{% url 'index' %}" name="Home">
                <img src={% static "movies/images/logo.png" %} width="150">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mx-auto custom-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'index' %}" name="Home">Main</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}" name="Home">G</a>
                    </li>
                </ul>
              
                <li class="nav-item dropdown no-arrow show">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                        <img class="img-profile rounded-circle" src="img/undraw_profile.svg">
                    </a>
                    <!-- Dropdown - User Information -->
                    <!-- <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in show" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                            Profile
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                            Settings
                        </a>
                        <a class="dropdown-item" href="#">
                            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                            Activity Log
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                            Logout
                        </a>
                    </div> -->
                </li>
                <div class="d-flex">
               
                </div>
            </div>
        </div>
    </nav>
</div>
{% endblock %}